[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mae5110"
version = "0.1.0"
description = "Course exercises for MAE 5110"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib",
    "numpy",
    "ruff"
]

[dependency-groups]
dev = [
    "pytest",
]

[project.scripts]
spokes_sweep = "mae5110.assignment_1:spokes_sweep"
inclination_sweep = "mae5110.assignment_1:inclination_sweep"
estimate_roa = "mae5110.assignment_1:estimate_roa"
return_map_plot = "mae5110.assignment_1:return_map_plot"
test_energy_conservation = "mae5110.assignment_1:test_energy_conservation"
test_flat_ground_dissipation = "mae5110.assignment_1:test_flat_ground_dissipation"
test_downhill_limit_cycle = "mae5110.assignment_1:test_downhill_limit_cycle"